version: '3'

services:
  kong:
    image: kong
    volumes: 
      - ./config:/usr/local/kong/declarative
      - ./plugins:/usr/local/custom/kong/plugins:rw
    environment: 
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.json
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,custom-auth
      KONG_LUA_PACKAGE_PATH: /usr/local/custom/?.lua;;
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000"
      - "127.0.0.1:7990:8001"
      - "8443:8443"
      - "127.0.0.1:8444:8444"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge